//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter Name")]
        public string Name { get; set; }
        public string UserName { get; set; }
        [Required(ErrorMessage = "Enter Email")]
        [EmailAddress (ErrorMessage ="Please enter a vaild email address")]
        public string Emailaddress { get; set; }

        [Required(ErrorMessage = "Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Select your role")]
        public string Role { get; set; }
        public string Resetpasswordcode { get; set; }
        public bool isactive { get; set; }
        public bool isblock { get; set; }

        [Required(ErrorMessage ="Password do not match")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        public string confirmpassword { get; set; }
    }
}
